name: Create CFF file
on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  create-cff:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setvars
      - name: Install FACILE-RS
        run: pip install FACILE-RS==3.0.0
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "marie.houillon@kit.edu"
      - name: Create CFF file
        run: facile-rs cff create
      - name: Archive CFF file
        uses: actions/upload-artifact@v4
        with:
          name: CFF-file
          path: ${{ env.CFF_PATH }}

  create-datacite:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setvars
      - name: Install FACILE-RS
        run: pip install FACILE-RS==3.0.0
      - name: Create DataCite metadata
        run: facile-rs datacite create
      - name: Upload DataCite metadata as artifact
        uses: actions/upload-artifact@v4
        with:
          name: DataCite-file
          path: ${{ env.DATACITE_PATH }}