name: Release workflow
on:
  push:
    tags:
      - 'v*'

jobs:
  generate-metadata:
    uses: ./.github/workflows/create-metadata.yml
  create-release:
    runs-on: ubuntu-22.04
    needs: generate-metadata
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setvars
      - uses: actions/download-artifact@v4
        # with:
        #   name: DataCite-file
      - name: Create GitHub release
        env:
          tag: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --generate-notes \
              ${{ env.DATACITE_PATH }}
      - name: Install FACILE-RS
        run: pip install FACILE-RS==3.0.0
      - name: Upload on Zenodo
        run: |
          if [ $ENABLE_ZENODO = true ];
          then
              echo facile-rs zenodo create 
          fi
