name: Release workflow
on:
  push:
    tags:
      - 'v*'

jobs:
  generate-metadata:
    uses: ./.github/workflows/create-metadata.yml
  github-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: DataCite-file
      - name: Create release
        env:
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --generate-notes \
              ${{ env.DATACITE_PATH }}
  archive-zenodo:
    runs-on: ubuntu-22.04
    if: env.ENABLE_ZENODO == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setvars
      - name: Install FACILE-RS
        run: pip install FACILE-RS==3.0.0
      - name: Prepare release
        run: facile-rs release prepare