name: Release workflow
on:
  push:
    tags:
      - 'v*'

jobs:
  generate-metadata:
    uses: ./.github/workflows/create-metadata.yml
  create-release:
    runs-on: ubuntu-22.04
    needs: generate-metadata
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setvars
      - uses: actions/download-artifact@v4
        with:
          name: DataCite-file
          pattern: '*.xml'
      - name: Rename DataCite file
        run: mv ${{ env.DATACITE_PATH }} ${{ env.DATACITE_RELEASE }}
      - name: Create GitHub release
        env:
          tag: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --generate-notes \
              ${{ env.DATACITE_RELEASE }}
      - name: Install FACILE-RS
        run: pip install FACILE-RS==${{ env.FACILE_RS_VERSION }}
      - name: Upload on Zenodo
        run: |
          if [ $ENABLE_ZENODO = true ];
          then
              facile-rs zenodo upload \
                ${{ env.RELEASE_ARCHIVE_URL }} \
                ${{ env.DATACITE_RELEASE }}
          fi
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}